#include <avr/pgmspace.h>
#include <string.h>
#include <Wire.h>
#include <Adafruit_GFX.h>
#include "Adafruit_LEDBackpack.h"

Adafruit_AlphaNum4 alpha4 = Adafruit_AlphaNum4();


const char flw_list_0[] PROGMEM = "zzzz";
const char flw_list_1[] PROGMEM = "";
const char flw_list_2[] PROGMEM = "ABACASBABEBIBYEDELETEUEYIDIELELYOSRARIUTYEYS";
const char flw_list_3[] PROGMEM = "ACEDERESHEHYIDLUMENERETS";
const char flw_list_4[] PROGMEM = "ADAHAMANAWDADIDSDYELENEYITOSRYVTZE";
const char flw_list_5[] PROGMEM = "AEONRORY";
const char flw_list_6[] PROGMEM = "AFARRO";
const char flw_list_7[] PROGMEM = "AGARASEDEEENERESGIGYHAINIOLULYMANANIOGONRAUE";
const char flw_list_8[] PROGMEM = "AHABEDEMISOY";
const char flw_list_9[] PROGMEM = "AIASDADEDSGALALELILSMEMSNENSNURNRSRTRYTSTU";
const char flw_list_10[] PROGMEM = "AJARAXAYEE";
const char flw_list_11[] PROGMEM = "AKASEDEEESIMIN";
const char flw_list_12[] PROGMEM = "ALAEANAPARASAYBABEBSCODOECEEEFERESEWEXFAFIFSFYGAIAICIEIFITIXKOKYLALILSLXLYMAMEMSODOEONOOOWPSSOTATOTSUMUSVAVYYS";
const char flw_list_13[] PROGMEM = "AMAHASBOBYENERESIAIDIEIIILINIRISLAMOOKOSPSURUSYEYL";
const char flw_list_14[] PROGMEM = "ANALANASCEDIDSDYESETEWGAGEGYIAILISKHNANENINONSNYOAONOWSASITATETITSUSYA";
const char flw_list_15[] PROGMEM = "APAYEDERESEXIAODOSPSSESOTS";
const char flw_list_16[] PROGMEM = "AQUA";
const char flw_list_17[] PROGMEM = "ARABAKALARBABSCHCOCSDADSEAEDEGELESETEWFSGHGOIAIDIEILINIOISIZKSLELYMSMYNANENINONYONOWPARISESYTETITSTYUMVOVYYLYN";
const char flw_list_18[] PROGMEM = "ASAPARCIEAHYIAKSPSSNST";
const char flw_list_19[] PROGMEM = "ATAPESMAOCOKOMOPTNTYUA";
const char flw_list_20[] PROGMEM = "AUASBEDIDYFSGYKSLALDNENTRATO";
const char flw_list_21[] PROGMEM = "AVALASDPELERESIDIEISIVONOSOW";
const char flw_list_22[] PROGMEM = "AWAYDLEDEEESFYKSLSNSNYOLRY";
const char flw_list_23[] PROGMEM = "AXALEDELESILISLEON";
const char flw_list_24[] PROGMEM = "AYAHESINREUS";
const char flw_list_25[] PROGMEM = "AZANONOVYM";
const char flw_list_26[] PROGMEM = "BAALASBABBBEBUBYCHCKCSDEDSELEZFFFTGHGSHSHTHUILITJAJUKEKULDLELILKLLLMLSLUMSNCNDNENGNINKNSNTPSPURBRDRERFRIRKRMRNRPRRRSRTRYSESHSKSSSTTETHTSTTTUUDUKURWDWLWNWRXYYEYSYT";
const char flw_list_27[] PROGMEM = "BEADAKAMANARATAUBECKDEDSDUEFENEPERESETGOGSINLALGLLLSLTLYMANDNENINJNNNSNTNZRERGRKRMRNRTSSSTTATETHTSVYYS";
const char flw_list_28[] PROGMEM = "BHAIATELUT";
const char flw_list_29[] PROGMEM = "BIASBBBIBSCEDEDIDSENERFFGAGGGSKEKOLELILKLLMANDNENGNINKNSNTOGOLOSRDRKRLRORRSESHSKSTTETOTSTTZE";
const char flw_list_30[] PROGMEM = "BLABADAEAGAHAMATAWAYEBEDEEETEWEYINIPITOBOCOGOTOWUBUEUMUR";
const char flw_list_31[] PROGMEM = "BOABAKARASATBABSCACKDEDSDYEPERETFFGSGYHOHRHSILISKEKOKSLALDLELLLOLTMAMBNANDNENGNKNNNYOBOHOKOLOMONOROSOTPSRARDRERGRKRMRNRSRTRUSESHSKSSTATETHTSTTUKUNUTWLWRWSXYYDYFYGYOYSZO";
const char flw_list_32[] PROGMEM = "BRADAEAGAKAMANASATAWAYEDEEEIENERETEWEYIAIEIGIKIMINIOISITNOODOGOKONOOOSOWUSUTUXYN";
const char flw_list_33[] PROGMEM = "BUATBABOBSBUCKDADDDIDODSFFFOGSHLHRIKKELBLKLLMFMPMSNANDNGNKNNNSNTOYRARBRDRGRKRLRNRPRRRSRTRYSHSKSSSTSYTETSTTYSZZ";
const char flw_list_34[] PROGMEM = "BYDEESKEOBRDRERLTE";
const char flw_list_35[] PROGMEM = "CAASBABSCACKCMDEDIDSFEFFGEGSGYIDINKEKYLELFLILKLLLMLOLPLVLXMAMEMIMOMPMSNENGNNNSNTNYPAPEPHPIPOPSPTRARBRDRERIRKRLRNRORPRRRSRTRYSASESHSISKSSSTTETITOTSTTTVTYUFUKULUMUPVAVEVYWKWSYEYS";
const char flw_list_36[] PROGMEM = "CEASBUCACEDEDIESILLELLLSLTNSNTPEPSRERFRNRORTSSTE";
const char flw_list_37[] PROGMEM = "CHADAIALAMANAOAPARASATAVAWAYEFEMENERETEVEWEZIAIBICIDIKINIPISITIVIZOCOGONOPOUOWUBUGUMURUT";
const char flw_list_38[] PROGMEM = "CIAODEDSELGSLLNEONRERLROSTTETOTSTYVE";
const char flw_list_39[] PROGMEM = "CLADAGAMANAPATAWAYEAEFEGEMEOEWIMIOIPITODOEOGONOPOTOUOWOYUBUEUJ";
const char flw_list_40[] PROGMEM = "CMOS";
const char flw_list_41[] PROGMEM = "COALATAXBBBSCACHCKCODADEDIDSDYEDFFFTGSHNHOIFILINIRITKEKYLALDLELLLOLSLTLYMAMBMEMMMPMSNDNENFNGNINKNNNSNTNYOFOKOLOMONOPOSOTPEPSPYRARDRERFRIRKRMRNRPRRRSRTRYSESHSSSTSYTETHTSTTUPURVEWKWLWPWSWYXAXYYSZEZY";
const char flw_list_42[] PROGMEM = "CRABAGAMANAPAWAYEDEEEMEWIAIBIMINISITOCOGOPOWUDUEUSUXUZ";
const char flw_list_43[] PROGMEM = "CUBABEBSDSEDESFFIFITKELLLMLTMSNTPSRBRDRERFRLRNRRRSRTSHSKSPSSTETS";
const char flw_list_44[] PROGMEM = "CYANSTTE";
const char flw_list_45[] PROGMEM = "CZAR";
const char flw_list_46[] PROGMEM = "DAALBSCECKCYDADEDODSELESFFFTGOGSHLHSISKSLELILLLSLTLYMEMNMPMSNANENGNINKNSNTPSRARBRERGRIRKRNRTSHSITATETOUBUDURUTVEVYWDWKWNWSWTYSZE";
const char flw_list_47[] PROGMEM = "DEADAFALANARAWBEBIBSBTCKCODEEDEKEMENEPERESETEVFIFOFTFYGSGUIDIFILJAKELALELFLILLLOLSLTMEMOMYNANENGNINSNTNYONPTRERKRMRNRORVSISKUSVAVIVSVYWSWYXYYS";
const char flw_list_48[] PROGMEM = "DHAKALOLOW";
const char flw_list_49[] PROGMEM = "DIALAMANBSCECHCKCTDIDODYEBEDELEMESETFFFSGSKAKELLMEMPMSNANENGNKNONSNTOLONORPSPTRERKRLRTSASCSHSKSSSTTATETSTTTZVAVEVIVOVSXIXYYA";
const char flw_list_50[] PROGMEM = "DJIN";
const char flw_list_51[] PROGMEM = "DOABATBSBYCKCOCSDEDIDODSDYEKENERESFFGEGSGYHAHSITJOLELFLLLSLTMEMSMYNANENGNNNSOBOKOLOMONOROSPAPEPSPYRARBRERIRKRMRORPRRRSRTRYSESHSISSSTTETHTITSTYUCUGUKUMUNUPURUTUXVEWDWFWLWNWPWSWTXYYSZEZY";
const char flw_list_52[] PROGMEM = "DRABACADAGAMAPATAWAYEEEGEKEWEYIBIPOPOWUBUDUGUMYS";
const char flw_list_53[] PROGMEM = "DSOS";
const char flw_list_54[] PROGMEM = "DUADALANARBSCECICKCTDEDSEDELESETFFGSITKAKEKYLELLLYMAMBMPNCNENGNKNNNSNTOSPEPSRARERNRORRSESHSKSTTY";
const char flw_list_55[] PROGMEM = "DWAM";
const char flw_list_56[] PROGMEM = "DYADANEDERESKENANE";
const char flw_list_57[] PROGMEM = "DZOS";
const char flw_list_58[] PROGMEM = "EACHDALENSRDRLRNRPRSSESTSYTHTSUSUXVE";
const char flw_list_59[] PROGMEM = "EBBABSENONRO";
const char flw_list_60[] PROGMEM = "ECADHEHOHTODOLONOSRUUS";
const char flw_list_61[] PROGMEM = "EDAMANDADIDODYEEENGEGYHSIEIKINITNAUC";
const char flw_list_62[] PROGMEM = "EECHLSLYOCRYVN";
const char flw_list_63[] PROGMEM = "EFFSTS";
const char flw_list_64[] PROGMEM = "EGADALANERGSGYISMAONOROS";
const char flw_list_65[] PROGMEM = "EHED";
const char flw_list_66[] PROGMEM = "EIDEKSLDNANERESH";
const char flw_list_67[] PROGMEM = "EKEDESKA";
const char flw_list_68[] PROGMEM = "ELANBABEDSEMEVFSGAHIIAIEKAKEKSLALELILSLYMAMOMSMYNAOYSASESISYTSVAYN";
const char flw_list_69[] PROGMEM = "EMESEUICILIRITMAMIMYOSPTUSYDYS";
const char flw_list_70[] PROGMEM = "ENCLCYDSESEWGSIDIFOLOSOWUFVY";
const char flw_list_71[] PROGMEM = "EOANNSRL";
const char flw_list_72[] PROGMEM = "EPEEHAICOS";
const char flw_list_73[] PROGMEM = "ERANASDAEDEKESEVGOGSHUICIEIKINISKSMANANENSNYOSRSSESTUVYN";
const char flw_list_74[] PROGMEM = "ESAUESKYMAMENEPYRASASESYTATS";
const char flw_list_75[] PROGMEM = "ETANASATCHENHEHSICNATATITYUI";
const char flw_list_76[] PROGMEM = "EUGEGHKSLAOIRO";
const char flw_list_77[] PROGMEM = "EVANENERESETEYIEILINOEOSVYYN";
const char flw_list_78[] PROGMEM = "EWANENERESKSTS";
const char flw_list_79[] PROGMEM = "EXAMECEDESITONPOUL";
const char flw_list_80[] PROGMEM = "EYASCKDEEDENERESNEOTRARERY";
const char flw_list_81[] PROGMEM = "EZRARI";
const char flw_list_82[] PROGMEM = "FAANASBEBSCECTDEDODSDYFFGSHDHSIKILINIRIXKELKLLLXMENDNENGNKNONSRARDRERLRMRORRRSRTSHSTTETSUNURUTUXVAVEWNWSYEYSZE";
const char flw_list_83[] PROGMEM = "FDIC";
const char flw_list_84[] PROGMEM = "FEALARATCKDSEBEDELENERESETGSHMHSISLLLTMEMSNDNINSNTODRDRERMRNSSSTTATETSTTUDUSWSYS";
const char flw_list_85[] PROGMEM = "FIARATBSCACECODEDODSEFERESFEFIFOGOGSJIKEKYLALELLLMLOLSNANDNENINKNNNONSQHRERKRMRNRSSCSHSKSTTSTTTZVEXTZZ";
const char flw_list_86[] PROGMEM = "FLABAGAKAMANAPATAWAXAYEAEDEEEGEMEWEXEYICIMINIPIRITIXOBOCOEOGOPOROWOXUBUEUSUX";
const char flw_list_87[] PROGMEM = "FOALAMBSCHCIENESFLGSGYHNIDILINLDLKLLNDNENSNTNZODOLOTPSRARBRDRERKRMRTSSUDULURUSWLXYYSZY";
const char flw_list_88[] PROGMEM = "FRABAEAGANAPASATAUAYEDEEEQETEYIBIGISITIZOEOGOMOSOWUGYE";
const char flw_list_89[] PROGMEM = "FUBSCICKDSELFFGSGUJILLMEMSMYNDNGNKNSRLRNRRRSRYSCSESSSTTZZEZZ";
const char flw_list_90[] PROGMEM = "GABEBIBSBYDEDIDSEAEDELENESFFGAGEGSIDILINIRITJOKSLALELLLSMAMBMEMPMSMYNENGNSNTOLPEPOPSPYRBRDRERIRSRTRVRYSHSPSTTETHTSUDULUMUNUPURUSVEWDWKWPWSYEYSZAZEZY";
const char flw_list_91[] PROGMEM = "GEALANARATCKDSEDEKEPESEZITLDLSLTMSNANENONSNTNUOGOMOSRERIRMRSRTRYSTTATSUM";
const char flw_list_92[] PROGMEM = "GHATEEIS";
const char flw_list_93[] PROGMEM = "GIANBBBEBSDEDSEDENESFFFTGAGIGOGSLALDLLLTMPNANGNKNNNONSOSPSRDRLRNRORRRTSHSMSTTETSVEZAZZ";
const char flw_list_94[] PROGMEM = "GJUS";
const char flw_list_95[] PROGMEM = "GLADAMEDEEEGEIENEYIAIBIDIMITOBOMOPOWUEUGUMUTYN";
const char flw_list_96[] PROGMEM = "GNARATAWOWUS";
const char flw_list_97[] PROGMEM = "GOADAFALASATBIBOBSBYDSELERESEYFFGHGOJILDLELFLPNENGNKNSODOFOGOKOLONOPOROSRARERIRMRPRYSHSSTHTOUKUTVSVTWDWFWKWLWNYAYS";
const char flw_list_98[] PROGMEM = "GRABADAMANATAVAYEEEGENEWEXEYIDIGIMINIPISITIZOGOKOTOWUBUEUMUS";
const char flw_list_99[] PROGMEM = "GUAMANARBSCKDEESFFGAIDLALELFLLLPLSLYMPMSNGNKNSPSRLRNRSRUSHSSSTTSVSYS";
const char flw_list_100[] PROGMEM = "GWENYN";
const char flw_list_101[] PROGMEM = "GYALMPMSRERIROTEVE";
const char flw_list_102[] PROGMEM = "HAAFAGARASBUCKDEDJDSEDEMENESETFFFTGGGSHAHNHSIKILINIRJIJJKAKEKULELFLILLLMLOLTMEMSNANDNGNKNSNTOSPSPURDRERKRLRMRNRORPRTRVSHSKSPSSSTTETHTSUDUFULUTVEWKWMWSYSZEZY";
const char flw_list_103[] PROGMEM = "HEADALAPARATBECHCKDADIDYEDELEPFTHSIDILIRLDLELLLMLOLPMEMPMSNDNSNTPSPTRARBRCRDRERLRMRNRORRRSRYSPSSSTTETHTSWEWNWSYS";
const char flw_list_104[] PROGMEM = "HICKDEEDESGHKELALDLILLLTMSNDNGNSNTOIPSPTRESHSNSSSTTSVEYAZZ";
const char flw_list_105[] PROGMEM = "HOARASAXBOBSCKDSEDERESFFGGGHGSHAHSIKKAKEKILDLELKLMLPLSLTLYMAMEMOMSMYNDNENGNKNSODOFOKONOPOROTPEPIPSRARERIRNRSRTSESPSSSTTETSUFURUTVEWEWFWKWLWSYAYSYT";
const char flw_list_106[] PROGMEM = "HUBEBSCKEDERESEYFFGEGHGOGSGYHSHUIAICISLALELKLLMAMEMFMPMSNGNHNKNSNTPSRLRTSHSKSOSSTSTU";
const char flw_list_107[] PROGMEM = "HWAN";
const char flw_list_108[] PROGMEM = "HYDEEDENESKELALEMNPEPOPSTE";
const char flw_list_109[] PROGMEM = "IAGOINMB";
const char flw_list_110[] PROGMEM = "IBBYEXIDIS";
const char flw_list_111[] PROGMEM = "ICBMEDERESHSKYON";
const char flw_list_112[] PROGMEM = "IDEAEEEMESLEOLYL";
const char flw_list_113[] PROGMEM = "IEEE";
const char flw_list_114[] PROGMEM = "IFFYNI";
const char flw_list_115[] PROGMEM = "IGADGSGYLUOR";
const char flw_list_116[] PROGMEM = "IKANATEYON";
const char flw_list_117[] PROGMEM = "ILEAEXIAKAKSLALSLYSASE";
const char flw_list_118[] PROGMEM = "IMAMHOIDMYPIPSUS";
const char flw_list_119[] PROGMEM = "INBYCACHCLDYESEZFOGAGEGOGSIAKSKYLYNANSRIROSTTITO";
const char flw_list_120[] PROGMEM = "IONANSTAWA";
const char flw_list_121[] PROGMEM = "IPSO";
const char flw_list_122[] PROGMEM = "IRANAQEDESIDISKSMAON";
const char flw_list_123[] PROGMEM = "ISACAKBABNISITLEMSNAOSSISY";
const char flw_list_124[] PROGMEM = "ITALASCHELEM";
const char flw_list_125[] PROGMEM = "IURE";
const char flw_list_126[] PROGMEM = "IVANARERIEOR";
const char flw_list_127[] PROGMEM = "IWIS";
const char flw_list_128[] PROGMEM = "IXIA";
const char flw_list_129[] PROGMEM = "IZAKARZY";
const char flw_list_130[] PROGMEM = "JAAPBSCKDADEFAGAGGGSILINKEKSMBMEMIMSNANENNNYPEPSRDRKRLRPRSSESPSSSYTOUKUPVAWSXYYEYSZYZZ";
const char flw_list_131[] PROGMEM = "JEANATDDDIEDELEPERESEZFEFFHULLNANINNNONSONRERIRKSSSTTETHTSUXWS";
const char flw_list_132[] PROGMEM = "JIAOBBBEBSFFGSLLLTMPNKNNNSNXRDSMVEVYZZ";
const char flw_list_133[] PROGMEM = "JOANBEBIBSBYCKCODIDYELESEYGSHNINJOKEKYLELILLLSLTLYMONENGNIOKRIRSRYSESHSISSSYTATSUKURVEWLWSYAYEYS";
const char flw_list_134[] PROGMEM = "JUANBABECODDDEDIDODSDYGAGSJUKEKULELILYMPNENGNKNOPERARERYSTTETSVE";
const char flw_list_135[] PROGMEM = "JYNX";
const char flw_list_136[] PROGMEM = "KAALASBSCKCYDEDIEDESFSGOGUHNIAIDIEIFIKILIMINISJAKAKIKSLALBLELIMAMEMINANENGNONSNTONPAPHRARERIRKRLRNRORPRTRYSSTATETHTITSTYTZVAWAWSYEYOYSZI";
const char flw_list_137[] PROGMEM = "KBAR";
const char flw_list_138[] PROGMEM = "KCAL";
const char flw_list_139[] PROGMEM = "KEANASBSCKDSEFEKELENEPETFSGSIRKSLELLLPLTMBMPNNNONSNTPIPSPTRBRFRIRKRNRORRSHSTTATETOTSWLYS";
const char flw_list_140[] PROGMEM = "KHAFANATETISORUD";
const char flw_list_141[] PROGMEM = "KIAHALBECKDDDSEFELEREVFFFSKELDLELLLNLOLPLTNANDNENGNKNONSPEPPPSRARIRKRNRSSHSSSTTETHTSVAWI";
const char flw_list_142[] PROGMEM = "KLANAPEEIKUX";
const char flw_list_143[] PROGMEM = "KNAGAPAREEEWITOBOPOTOWOXUBURUT";
const char flw_list_144[] PROGMEM = "KOANAPASBEBOBSCHELFFHAHLISJIKALALONDNGNKNSOKPHPSRARERIRORSRTRURYSSTOWS";
const char flw_list_145[] PROGMEM = "KRABISOC";
const char flw_list_146[] PROGMEM = "KSAR";
const char flw_list_147[] PROGMEM = "KUDODUEHESFIHNIAKULANANERDRIRTRUTATITUZU";
const char flw_list_148[] PROGMEM = "KVAS";
const char flw_list_149[] PROGMEM = "KYAKARATBOESLALENDNEPETEUS";
const char flw_list_150[] PROGMEM = "LABSCECKCSCYDEDSDYERGSHSICIDIKINIRKEKHKYLLLOMAMBMEMPMSNANDNENGNINKNTNXPPPSRARDRERIRKRNRSSESHSSSTTETHTITSTUUDUEUFVAVEVSWKWNWSYSZEZOZY";
const char flw_list_151[] PROGMEM = "LEADAFAHAKALAMANAPARASATCHDAEDEKEPERESETFTGOGSHRIAIFIRISKEKSKULAMENANDNGNONSNTONPSPTRERPSASSSTTATSUDVAVEVIVOVYWDXIXYYSZZ";
const char flw_list_152[] PROGMEM = "LIAMANARASBSCECHCKDADODSEDEFENERESEUFEFOFTGSKELALLLOLTLYMAMBMEMNMOMPMYNANCNDNENGNKNNNONSNTNYONPAPEPOPSRARERIRKSASESKSPSSSTTATETHTSTUVAVEVYZA";
const char flw_list_153[] PROGMEM = "LOADAFAMANBEBIBOBSCACHCICKCODEDSDZEBFTGEGOGSGYIDINIRISKEKILALLMAMBMENANENGNIOFOKOMONOPOROSOTPEPSRARDRERIRNRYSESHSSSTTATETHTITOTSTTUDUNUPURUSUTVEWEWNWPWSWTYDYS";
const char flw_list_154[] PROGMEM = "LUAUBECACECICKCYDEDODSESFFGEGSISITKELALLLUMAMPMSNANDNENGNKNTNYPERARERKRSSASHSKSTTETZVSXE";
const char flw_list_155[] PROGMEM = "LWEI";
const char flw_list_156[] PROGMEM = "LYAMCHDAESLEMENNNXONRARESETE";
const char flw_list_157[] PROGMEM = "MAARASBECECHCKCSCYDADEDSDYESGEGGGIGSHAIAIDIKILIMINIRJEKEKIKOKSLALELILLLMLSLTMAMEMSNANDNENGNINNNONSNXNYPSRARCRDRERGRIRJRKRLRMRSRTRVRXRYSASCSESHSKSSSTSUTATETHTSTTTYUDUIULUNUTWKWNWRWSXIXYYAYEYOYSZEZY";
const char flw_list_158[] PROGMEM = "MEADALANASATCKDSEDEKERESETFFGAGSINIRLALDLLLSLTMEMOMSNDNENGNONSNTNUOUOWRCRERIRKRLRVSASESHSSTATETHTSUSVEWLWSZEZZ";
const char flw_list_159[] PROGMEM = "MHOS";
const char flw_list_160[] PROGMEM = "MIBSCACECHCKCOCSDIDSENFFGGGSHAHIKELDLELFLKLLLOLSLTMDMEMINANDNENGNINKNNNONTNXNYPSRARERIRKRORSRVRYSCSESOSSSTTETTTYXTXYZZ";
const char flw_list_161[] PROGMEM = "MNAS";
const char flw_list_162[] PROGMEM = "MOAIANASATBEBSBYCHCKCSDEDIDSENERESFOGSHOHRILITJOKEKIKOLALDLELLLSLTLYMEMIMSNANGNKNONSNTNYODOGOIOKOLONOPOROSOTPEPSPYRARDRERNRORSRTSESHSKSSSTTETHTITSTTTUUEUPUSVEWAWNWSXAYAYLYSZEZOZZ";
const char flw_list_163[] PROGMEM = "MUCHCKDSFFFIGGGSIDILIRLELLMMMPMSMUNGNINSNTONRARERKRLRRSESHSKSOSSSTTETITSTTZOZZ";
const char flw_list_164[] PROGMEM = "MWAH";
const char flw_list_165[] PROGMEM = "MYALCACSERLONARASTTHXO";
const char flw_list_166[] PROGMEM = "MZEE";
const char flw_list_167[] PROGMEM = "NAAMANBEBKBSCHCLDADSDYFFGAGSGYIFIKILINIRLAMEMSMUNANENGNINSOIOSPAPEPSRARCRDRERIRKRYSASHTATETLTOTSURVEVYYSZEZI";
const char flw_list_168[] PROGMEM = "NCAA";
const char flw_list_169[] PROGMEM = "NEALAPARATBRBSCKDADIDSEDELEMEPFSGSIFILKSLLLSMAMNNEONPSRDRFRKRORTSHSSSTTETSTTUKUMUTVAVEVIWSWTXT";
const char flw_list_170[] PROGMEM = "NGAI";
const char flw_list_171[] PROGMEM = "NIALBSCECKCODEDIDSEDEFELESFEFFGHKEKIKOLELLLSMBMSNANEPAPSRLSHSITATETSXEXY";
const char flw_list_172[] PROGMEM = "NOAAAHAKAMBEBSBYCKDEDIDSELESGGGSILIRLALELLLOMAMEMIMSNANENGNIOBOKONOPPERARIRKRMRWSESHSYTATETTULUNUPUSUTVAWLWNWSWTWYYS";
const char flw_list_173[] PROGMEM = "NUBSDEFFKELLMBNSRDRLTS";
const char flw_list_174[] PROGMEM = "OAFSHUKSKYRSRYSTTHTSTY";
const char flw_list_175[] PROGMEM = "OBASEDESEYIAIEISITOEOLOS";
const char flw_list_176[] PROGMEM = "OCASHETA";
const char flw_list_177[] PROGMEM = "ODAHALASDSEAERESEYICIEINISOMORSOYL";
const char flw_list_178[] PROGMEM = "OEMS";
const char flw_list_179[] PROGMEM = "OFAYFSFY";
const char flw_list_180[] PROGMEM = "OGAMEELERE";
const char flw_list_181[] PROGMEM = "OHEDIAIOMSSA";
const char flw_list_182[] PROGMEM = "OIKSLSLYNKNTSE";
const char flw_list_183[] PROGMEM = "OKASAYEHESLARATA";
const char flw_list_184[] PROGMEM = "OLAFAGAVDEDSDYEAEGENEOESGAIAIDINIOIYLALYMSPEVA";
const char flw_list_185[] PROGMEM = "OMANARBUENERITNIOVSK";
const char flw_list_186[] PROGMEM = "ONCEERESIELYOSSTTOUSYX";
const char flw_list_187[] PROGMEM = "OOFSFYHSMSNANSNTPSRTSESYTSZEZY";
const char flw_list_188[] PROGMEM = "OPAHALECEDELENESPOTSUS";
const char flw_list_189[] PROGMEM = "ORADALANBSBYCACSDODSEGELENEOESFEFSGYIGINLELYRASATSYXZO";
const char flw_list_190[] PROGMEM = "OSARESHALOSA";
const char flw_list_191[] PROGMEM = "OTESHAHOICISOHTO";
const char flw_list_192[] PROGMEM = "OUCHDSKSLDLKMAPAPHPSRNRSSTTSZO";
const char flw_list_193[] PROGMEM = "OVALELENERIDUM";
const char flw_list_194[] PROGMEM = "OWEDENERESLSLYNSRESETS";
const char flw_list_195[] PROGMEM = "OXENERESIDIMUS";
const char flw_list_196[] PROGMEM = "OYERESEZ";
const char flw_list_197[] PROGMEM = "OZZY";
const char flw_list_198[] PROGMEM = "PAALANCACECKCOCSCTCYDIDSGEHSIDIKILINIRISLELLLMLOLPLSLYMSNDNENGNSNTPAPEPSRARCRDRERKRPRRRSRTSESHSOSSSTTETHTSTUTYUAULVEVSWAWKWLWNWSYS";
const char flw_list_199[] PROGMEM = "PEAGAKALANARASATBACHCKCSDSEDEKELENEPERESGHGSHSINKELALELFLLLSLTNANDNENINKNNNSNTONPEPIPOPSRERIRKRLRMRNRPRTRURVSOSTTATETRTSWS";
const char flw_list_200[] PROGMEM = "PFUI";
const char flw_list_201[] PROGMEM = "PHATEWILIPISIZOHONOSOTUTYS";
const char flw_list_202[] PROGMEM = "PIAFALANASCACECKCSCTEDERESETGSKAKEKILALELILLLYMAMPNANENGNKNSNTNYONOYPAPEPIPSPYRLRNRSSASESHSOSSTATHTSTTTYUMUSXYZE";
const char flw_list_203[] PROGMEM = "PLANAPATAYEAEBEDEWEXIEIMODOPOTOWOYUEUGUMUS";
const char flw_list_204[] PROGMEM = "POASCKCODSEMEPETGOGYISKEKYLELKLLLOLSLTLYMEMOMPMSNDNENGNKNSNTNYODOFOHOKOLONOPOROSOTPEPSRERKRNRTRYSESHSSSTSYTETSTTUFUKULURUTWNWSXYZZ";
const char flw_list_205[] PROGMEM = "PRADAMAOATAUAYEEEFEMENEPESEXEYEZIGIMISOAOBODOFOGOMONOOOPOSOVOWUEUHUTYS";
const char flw_list_206[] PROGMEM = "PSIS";
const char flw_list_207[] PROGMEM = "PTAHUI";
const char flw_list_208[] PROGMEM = "PUBEBSCECKDSDUERFFGHGSHAIRJAKAKEKUKYLALELILKLLLPLSLULYMAMPMYNANGNKNSNTNYPAPSPURERIRLRRRSSHSSTSTTTZYS";
const char flw_list_209[] PROGMEM = "PYASATESETICINLENEOTRERO";
const char flw_list_210[] PROGMEM = "QADIIDTS";
const char flw_list_211[] PROGMEM = "QINS";
const char flw_list_212[] PROGMEM = "QOPH";
const char flw_list_213[] PROGMEM = "QUADAGAIATAYEPEYIDIMINIPITIZODOPOT";
const char flw_list_214[] PROGMEM = "RABICACECHCKCYDEDSFAFEFFFIFTGAGEGGGIGSGUHSIAIDIKILINISITJAKEKIKULELFMAMIMOMPMSNANDNGNINKNTPEPSPTRERKSESHSPSTTATETHTOTSTUULUNVEVIVSWNWSYAYEYSZEZZ";
const char flw_list_215[] PROGMEM = "READAKALAMANAPARBABEBSCDCKCSDDDEDODSEDEFEKELENESFSFTGOGSHSIDIFIKINISITKELYMSMYNANDNENKNONSNTNYOSPOPPPSSHSPSTTATETSUBVAVSWS";
const char flw_list_216[] PROGMEM = "RHEAEEOSUS";
const char flw_list_217[] PROGMEM = "RIADALASBABSCACECHCICKCOCYDEDSELEMFEFFFSFTGAGGGSKILELLMAMEMSMUMYNANDNENGNKNSOTPEPPPSPTSASCSESKSPTATETSTTTZVAVEVIVOVYZA";
const char flw_list_218[] PROGMEM = "ROADAMANARBBBEBSBTBYCHCKCSDADDDEDIDSEDESFLILINJIKEKSKYLELFLLMAMEMPMSMYNANENGNTNZODOFOKOMONOPOSOTPEPYRARERIRTRYSASESSSTSYTATCTETHTITLTOTSUEULUMUPUTUXVEWEWSWTXIXYZE";
const char flw_list_219[] PROGMEM = "RUBEBIBSBYCKCSDDDEDSDYEDERESFEFFGAGSHRINIZKHLELYMEMPMSNDNENGNSNTRPRUSASESHSKSSSTTHTS";
const char flw_list_220[] PROGMEM = "RYALANASESFEKENDONOTPEUN";
const char flw_list_221[] PROGMEM = "SAABAGARBABEBSCKCSDADEDIDODRDSFEFTGAGEGOGSGYICIDILIMINIRISKEKILELKLLLPLSLTLZMAMEMPMSNANDNENGNKNSNTPSRARDRIRKRSSESHSKSSTETIUDULUTVEVSWNWSXEYS";
const char flw_list_222[] PROGMEM = "SCABADAGAMANARATAWOGOPOTOWUDUGULUMUPURUTYE";
const char flw_list_223[] PROGMEM = "SEALAMANARASATCHCOCSCTCYEDEKELEMENEPERESGOGSIFIKILIRISKAKTLALDLELFLLLSMEMINANDNENSNTPSPTRARBRERFRKRRRSSESHSSTATHTSTTWNWSXTXYYS";
const char flw_list_224[] PROGMEM = "SHADAEAGAHAMANATAWAYEAEDELEMEPERESETEWIMINIPIRITIVODOEOGOOOPOTOWULUNUTWA";
const char flw_list_225[] PROGMEM = "SIALAMBBBSCECHCKCSDADEDHDSENESFTGHGNJOKAKEKHLDLELKLLLOLTMAMDMIMPMSNDNENGNHNKNSPEPSRERIRSSSSTTETHTSTUTZVAZEZY";
const char flw_list_226[] PROGMEM = "SJOE";
const char flw_list_227[] PROGMEM = "SKAGASATAWEEEGENEOEPERETEWIDIMINIOIPISITOLUAUGYEYFYR";
const char flw_list_228[] PROGMEM = "SLABAEAGAMAPATAVAWAYEBEDEEEWEYIDIMIPITOBOEOGOPOTOWUBUEUGUMURUT";
const char flw_list_229[] PROGMEM = "SMEEEWIRITOGUGURUT";
const char flw_list_230[] PROGMEM = "SNABAGAPARAWEBEDEEIBIGIPITOBODOGOTOWUBUGYE";
const char flw_list_231[] PROGMEM = "SOAKAPARBABSCACKCSDADSFAFTGSHOHSILJAKELALDLELILOLSMAMEMSMYNENGNSNYOKOLOMONOPOTPHPSRARBRDRERIRNRTSASSTHTOTSUKULUMUPURUSUTVSWFWLWMWNWPWSYAYS";
const char flw_list_232[] PROGMEM = "SPAEAGAMANARASATAWAYAZECEDEKETEWICIEIFIKIMINITIVODOTRYUDUEUGUNUR";
const char flw_list_233[] PROGMEM = "SRIS";
const char flw_list_234[] PROGMEM = "STABAGANAPARATAWAYEDEMENEPETEWEYIEIMIROAOBOLOPOTOWUBUDUMUNYEYX";
const char flw_list_235[] PROGMEM = "SUBABJBSCHCKDDDSEDERESETEZFIGHGOGSIDITKHKIKSLALKLUMOMPMSMYNGNINKNNNSPEPPPSPTQSRARDRERFSISSSUSYVAZIZY";
const char flw_list_236[] PROGMEM = "SVEN";
const char flw_list_237[] PROGMEM = "SWABADAGAKAMANAPATAYEDEEENEYIGIMIZOBOPOTUM";
const char flw_list_238[] PROGMEM = "SYKENC";
const char flw_list_239[] PROGMEM = "TAALBBBIBSBUCECHCKCOCTDDDSEDELESFTGSHAHRIGILINISITKAKEKIKSKYLALCLELILKLLMEMIMPMSNANENGNHNINKNNNSOSPAPEPSPURARERNRORPRSRTSHSKSSTETHTSTTTUUSUTVAVSWAWSWTXAXIYS";
const char flw_list_240[] PROGMEM = "TEADAKALAMARASATCHCSDDDIDSDYEDEKELEMENERESFFFLFSGGGSGUHRILINLALDLELLLSLTMEMPMSNDNENNNSNTPARARFRIRMRNRRSLSSSTTETHTSWSXT";
const char flw_list_241[] PROGMEM = "THADAEAIANARATAWEAEEEMENEOEWEYIAIGINIOIRISOMONOROURUUDUGURUS";
const char flw_list_242[] PROGMEM = "TIANARCECHCKCSDEDSDYEDERESFFFTGEGSKAKEKIKSLELLLSLTMEMINANDNENGNKNSNTNYPIPSPTRERLROSHTETITOTS";
const char flw_list_243[] PROGMEM = "TOADBEBIBYCKCOCSDDDSDYEAEDESEYFFFTFUGAGEGOGSHOILITJOKEKOLALDLELLLTLUMAMBMEMIMOMSNENGNINKNSNYOKOLOMONOTPEPHPIPOPSRARCRERIRNRORRRSRTRYSASESHSSSTTETOTSUKUNURUTVAVEWNWSWTWYYOYSZE";
const char flw_list_244[] PROGMEM = "TRADAMANAPATAYEEEFEKESETEVEWEYEZIEIGIMINIOIPISIXODOGONOPOTOWOYUEUGYEYP";
const char flw_list_245[] PROGMEM = "TSAR";
const char flw_list_246[] PROGMEM = "TUANBABEBSCKFAFFFTGSISLELLMPMSNANDNENGNSNYPIPSRDRFRKRMRNSHSKTSTUZZ";
const char flw_list_247[] PROGMEM = "TWAEALASATAYEEIGINITOS";
const char flw_list_248[] PROGMEM = "TYBIDEEDEEERESGSINKEMPNDNEPEPO";
const char flw_list_249[] PROGMEM = "TZAR";
const char flw_list_250[] PROGMEM = "UDALONOS";
const char flw_list_251[] PROGMEM = "UEYS";
const char flw_list_252[] PROGMEM = "UGLY";
const char flw_list_253[] PROGMEM = "UKES";
const char flw_list_254[] PROGMEM = "ULANESEXLANAUSVA";
const char flw_list_255[] PROGMEM = "UMBOMAPHPSPYRAUS";
const char flw_list_256[] PROGMEM = "UNAICECICODEDODYISITIVIXTO";
const char flw_list_257[] PROGMEM = "UPASBYDOGOONSYTA";
const char flw_list_258[] PROGMEM = "URALAOBSDEDSDUDYEAESEYGEICNSPSSAUSVA";
const char flw_list_259[] PROGMEM = "USEDER";
const char flw_list_260[] PROGMEM = "UTAHESISUS";
const char flw_list_261[] PROGMEM = "UVAEASEA";
const char flw_list_262[] PROGMEM = "VACSDEESGIGSILINIRLELIMPNENGNSNTRARERSRYSESTTSTUUSUTVSWS";
const char flw_list_263[] PROGMEM = "VEALDAEPERESGAGOHMILINLALDLELLNANDNNNTRARBRDRERNRSRTRYSTTOTSXT";
const char flw_list_264[] PROGMEM = "VIAEALASBEBSCECKDADEDSEDERESETEWGAGSIIKILALDLELLMSNANENONSNTNYOLRERLSASETATETOVAVEVIVOZY";
const char flw_list_265[] PROGMEM = "VLADEIOG";
const char flw_list_266[] PROGMEM = "VOARESIDIPLALELKLSLTRSTEWS";
const char flw_list_267[] PROGMEM = "VRILOTOUOW";
const char flw_list_268[] PROGMEM = "VTOL";
const char flw_list_269[] PROGMEM = "VUGGGHGSLGLNMS";
const char flw_list_270[] PROGMEM = "VYKY";
const char flw_list_271[] PROGMEM = "WAACBSCKCODDDEDIDSDTDYESFFFSFTGEGSHLIDIFILINIRISITKAKEKFLDLELILKLLLTLYMENDNENGNKNSNTNYPSQFRBRDRERKRMRNRPRSRTRYSESHSPSTTETSTTUKULURVEVYWAWEWLWSXYYS";
const char flw_list_272[] PROGMEM = "WEAKALANARBBBSDSEDEKELEMENEPERESETFTHRIDILIRKALDLKLLLSLTMBMSNANDNSNTPTRERORTSTTATSXEYS";
const char flw_list_273[] PROGMEM = "WHAEAMAPATEEENETEWEYIDIGIMINIOIPIRITIZOAOMOPOTOWUPYS";
const char flw_list_274[] PROGMEM = "WICECHCKDEELERFEGSKILDLELILLLTLYMPNDNENGNINKNNNONSNYPERERYSCSESHSPSSSTTETHTSTTVE";
const char flw_list_275[] PROGMEM = "WOADCKESFSGSKEKSLDLFMBNGNKNSNTODOFOLONOSOTPSRDRERKRMRNRTSTTSVEWFWS";
const char flw_list_276[] PROGMEM = "WRAPENIT";
const char flw_list_277[] PROGMEM = "WUDSDULLSS";
const char flw_list_278[] PROGMEM = "WYCHESLENDNNNSTE";
const char flw_list_279[] PROGMEM = "XENA";
const char flw_list_280[] PROGMEM = "XIAN";
const char flw_list_281[] PROGMEM = "XMAS";
const char flw_list_282[] PROGMEM = "XRAY";
const char flw_list_283[] PROGMEM = "XYST";
const char flw_list_284[] PROGMEM = "YAARBACCCKDSFFGIGSHSKSLDLELUMSNGNKPPPSRDRERKRNRRTEUDUPWLWNWPWSWYYS";
const char flw_list_285[] PROGMEM = "YBET";
const char flw_list_286[] PROGMEM = "YEADAHANARASBOCHDEEDGGLDLKLLLMLPLTNSPSRDRKSKSTTITTUKVEWS";
const char flw_list_287[] PROGMEM = "YIDSKENSPEPSRDRKRRTE";
const char flw_list_288[] PROGMEM = "YMPT";
const char flw_list_289[] PROGMEM = "YNESEZ";
const char flw_list_290[] PROGMEM = "YOBSCKDADEDHDSGAGHGIKEKOKSLDLKMPNDNGNINTOFOPRERKRPSTUKURUSWEWLWS";
const char flw_list_291[] PROGMEM = "YUANBACACHCKFTGAGOGSKEKIKOKSKYLEMAMPNXPSRIRTTZZU";
const char flw_list_292[] PROGMEM = "YVESONOR";
const char flw_list_293[] PROGMEM = "YWHAIS";
const char flw_list_294[] PROGMEM = "ZACHCKGSNENYPSRARFRITI";
const char flw_list_295[] PROGMEM = "ZEALASBUDSESINKEKSLSNANOPSRKROSTTAUSZE";
const char flw_list_296[] PROGMEM = "ZIBOFFGSLALLMBNCNENGNSONPSTATETITSZZ";
const char flw_list_297[] PROGMEM = "ZOBOBUICLANENKOMONOSOTRARIRNUK";
const char flw_list_298[] PROGMEM = "ZULUNIPA";
const char flw_list_299[] PROGMEM = "ZYME";
// Then set up a table to refer to your strings.

const char *const string_table[] PROGMEM = { flw_list_0,
  flw_list_1, flw_list_2, flw_list_3, flw_list_4, flw_list_5, flw_list_6, flw_list_7, flw_list_8, flw_list_9, flw_list_10,
flw_list_11, flw_list_12, flw_list_13, flw_list_14, flw_list_15, flw_list_16, flw_list_17, flw_list_18, flw_list_19, flw_list_20,
flw_list_21, flw_list_22, flw_list_23, flw_list_24, flw_list_25, flw_list_26, flw_list_27, flw_list_28, flw_list_29, flw_list_30,
flw_list_31, flw_list_32, flw_list_33, flw_list_34, flw_list_35, flw_list_36, flw_list_37, flw_list_38, flw_list_39, flw_list_40,
flw_list_41, flw_list_42, flw_list_43, flw_list_44, flw_list_45, flw_list_46, flw_list_47, flw_list_48, flw_list_49, flw_list_50,
flw_list_51, flw_list_52, flw_list_53, flw_list_54, flw_list_55, flw_list_56, flw_list_57, flw_list_58, flw_list_59, flw_list_60,
flw_list_61, flw_list_62, flw_list_63, flw_list_64, flw_list_65, flw_list_66, flw_list_67, flw_list_68, flw_list_69, flw_list_70,
flw_list_71, flw_list_72, flw_list_73, flw_list_74, flw_list_75, flw_list_76, flw_list_77, flw_list_78, flw_list_79, flw_list_80,
flw_list_81, flw_list_82, flw_list_83, flw_list_84, flw_list_85, flw_list_86, flw_list_87, flw_list_88, flw_list_89, flw_list_90,
flw_list_91, flw_list_92, flw_list_93, flw_list_94, flw_list_95, flw_list_96, flw_list_97, flw_list_98, flw_list_99, flw_list_100,
flw_list_101, flw_list_102, flw_list_103, flw_list_104, flw_list_105, flw_list_106, flw_list_107, flw_list_108, flw_list_109, flw_list_110,
flw_list_111, flw_list_112, flw_list_113, flw_list_114, flw_list_115, flw_list_116, flw_list_117, flw_list_118, flw_list_119, flw_list_120,
flw_list_121, flw_list_122, flw_list_123, flw_list_124, flw_list_125, flw_list_126, flw_list_127, flw_list_128, flw_list_129, flw_list_130,
flw_list_131, flw_list_132, flw_list_133, flw_list_134, flw_list_135, flw_list_136, flw_list_137, flw_list_138, flw_list_139, flw_list_140,
flw_list_141, flw_list_142, flw_list_143, flw_list_144, flw_list_145, flw_list_146, flw_list_147, flw_list_148, flw_list_149, flw_list_150,
flw_list_151, flw_list_152, flw_list_153, flw_list_154, flw_list_155, flw_list_156, flw_list_157, flw_list_158, flw_list_159, flw_list_160,
flw_list_161, flw_list_162, flw_list_163, flw_list_164, flw_list_165, flw_list_166, flw_list_167, flw_list_168, flw_list_169, flw_list_170,
flw_list_171, flw_list_172, flw_list_173, flw_list_174, flw_list_175, flw_list_176, flw_list_177, flw_list_178, flw_list_179, flw_list_180,
flw_list_181, flw_list_182, flw_list_183, flw_list_184, flw_list_185, flw_list_186, flw_list_187, flw_list_188, flw_list_189, flw_list_190,
flw_list_191, flw_list_192, flw_list_193, flw_list_194, flw_list_195, flw_list_196, flw_list_197, flw_list_198, flw_list_199, flw_list_200,
flw_list_201, flw_list_202, flw_list_203, flw_list_204, flw_list_205, flw_list_206, flw_list_207, flw_list_208, flw_list_209, flw_list_210,
flw_list_211, flw_list_212, flw_list_213, flw_list_214, flw_list_215, flw_list_216, flw_list_217, flw_list_218, flw_list_219, flw_list_220,
flw_list_221, flw_list_222, flw_list_223, flw_list_224, flw_list_225, flw_list_226, flw_list_227, flw_list_228, flw_list_229, flw_list_230,
flw_list_231, flw_list_232, flw_list_233, flw_list_234, flw_list_235, flw_list_236, flw_list_237, flw_list_238, flw_list_239, flw_list_240,
flw_list_241, flw_list_242, flw_list_243, flw_list_244, flw_list_245, flw_list_246, flw_list_247, flw_list_248, flw_list_249, flw_list_250,
flw_list_251, flw_list_252, flw_list_253, flw_list_254, flw_list_255, flw_list_256, flw_list_257, flw_list_258, flw_list_259, flw_list_260,
flw_list_261, flw_list_262, flw_list_263, flw_list_264, flw_list_265, flw_list_266, flw_list_267, flw_list_268, flw_list_269, flw_list_270,
flw_list_271, flw_list_272, flw_list_273, flw_list_274, flw_list_275, flw_list_276, flw_list_277, flw_list_278, flw_list_279, flw_list_280,
flw_list_281, flw_list_282, flw_list_283, flw_list_284, flw_list_285, flw_list_286, flw_list_287, flw_list_288, flw_list_289, flw_list_290,
flw_list_291, flw_list_292, flw_list_293, flw_list_294, flw_list_295, flw_list_296, flw_list_297, flw_list_298, flw_list_299

};

char buffer[512];  // make sure this is large enough for the largest string it must hold



int setuprun = 0;


void setup() {
  // put your setup code here, to run once:
  //Serial.begin(9600);
//  while (!Serial) ; // wait for serial
//  delay(200);
  //Serial.println("FLW Test");
  //Serial.println("-------------------");
   randomSeed(analogRead(0));
   
//  setuprun +=1;
//  if( setuprun >1 ) {
//    Serial.println(" Setup ran to many times!");
//    while(1) {
//      
//    }
//  }
 // alpha4.setBrightness(2);
  alpha4.begin(0x70);  // pass in the address

  alpha4.setBrightness(2);

  alpha4.writeDigitRaw(3, 0x0);
  alpha4.writeDigitRaw(0, 0xFFFF);
  alpha4.writeDisplay();
  delay(200);
  alpha4.writeDigitRaw(0, 0x0);
  alpha4.writeDigitRaw(1, 0xFFFF);
  alpha4.writeDisplay();
  delay(200);
  alpha4.writeDigitRaw(1, 0x0);
  alpha4.writeDigitRaw(2, 0xFFFF);
  alpha4.writeDisplay();
  delay(200);
  alpha4.writeDigitRaw(2, 0x0);
  alpha4.writeDigitRaw(3, 0xFFFF);
  alpha4.writeDisplay();
  delay(200);
  
  alpha4.clear();
  alpha4.writeDisplay();

  alpha4.writeDigitAscii(1, 'F');
  alpha4.writeDigitAscii(2, 'L');
  alpha4.writeDigitAscii(3, 'W');
  alpha4.writeDisplay();
  delay(500);

}


/* Using the string table in program memory requires the use of special functions to retrieve the data.
     The strcpy_P function copies a string from program space to a string in RAM ("buffer").
     Make sure your receiving string in RAM is large enough to hold whatever
     you are retrieving from program space. */

//void list_all_flw() {
//  //while(1) {
//    for (int i = 1; i <= 299; i++) {
//      strcpy_P(buffer, (char *)pgm_read_word(&(string_table[i])));  // Necessary casts and dereferencing, just copy.
//      for( int x=2; x<strlen(buffer); x=x+2 ) {
//        Serial.print(i);
//        Serial.print(", ");
//        Serial.print(x);
//        Serial.print(" ");
//        Serial.print(buffer[0]);
//        Serial.print(buffer[1]);
//        Serial.print(buffer[x]);
//        Serial.println(buffer[x+1]);
//        delay(500);
//      }
//    }
//  //}
//}

//void list_rnd_flw(){
//  int x;
//  int i;
//  //while(1) {
//    i = random(1,300);
//    strcpy_P(buffer, (char *)pgm_read_word(&(string_table[i])));  // Necessary casts and dereferencing, just copy.
//       
//    x = random( 2,((strlen(buffer)-2)/2)+1);
//    Serial.print(buffer[0]);
//    Serial.print(buffer[1]);
//    Serial.print(buffer[x]);
//    Serial.println(buffer[x+1]);
//    //Serial.print(" - i=");
//    //Serial.print(i);
//    //Serial.print(" - strlen=");
//    //Serial.print(strlen(buffer));
//    //Serial.print(" - x=");
//    //Serial.println(x);
//    
//    delay(500);
//      
//  //}
//}

void list_rnd_sol_flw(){
  int x;
  int i;
  char tbuff[5];
  char obuff[5];
  i = random(1,300);
  strcpy_P(buffer, (char *)pgm_read_word(&(string_table[i])));  // Necessary casts and dereferencing, just copy.
  
  int len = ((strlen(buffer)-2)/2)+1 ;
  x = random( 2,len);
  
  //Serial.println("i -- x -- len");
  //Serial.println(i);
  //Serial.println(x);
  //Serial.println(len);
  //Serial.println();

  for( i=0; i<4; i++ ) {
    obuff[i] = ' ';
  }

  tbuff[0] = buffer[0];
  tbuff[1] = buffer[1];
  tbuff[2] = buffer[x];
  tbuff[3] = buffer[x+1];
  tbuff[4] = 0x00;
  obuff[4] = 0x00;
  
  int count = 0;
  while(1) {
    i=random(0,4);

    if( obuff[i] == ' ' ) {
      obuff[i] = tbuff[i];
      count +=1 ;
    } else 
      continue;  
    
//    Serial.println(obuff);
    //Serial.print('\r');
    //delay(500);

 // set every digit to the buffer
  alpha4.writeDigitAscii(0, obuff[0]);
  alpha4.writeDigitAscii(1, obuff[1]);
  alpha4.writeDigitAscii(2, obuff[2]);
  alpha4.writeDigitAscii(3, obuff[3]);
 
  // write it out!
  alpha4.writeDisplay();
  delay(500);
    
    if( count == 4 ) break;
  }
//  Serial.println("");
  delay(2500);
}

//void myWrite( char buff, int myDelay ){
// char obuff[5];
//  
// // set every digit to the buffer
//  alpha4.writeDigitAscii(0, obuff[0]);
//  alpha4.writeDigitAscii(1, obuff[1]);
//  alpha4.writeDigitAscii(2, obuff[2]);
//  alpha4.writeDigitAscii(3, obuff[3]);
// 
//  // write it out!
//  alpha4.writeDisplay();
//}

void loop() {
  // put your main code here, to run repeatedly:

  while(1) {
    //list_rnd_flw();
    //list_all_flw();
    list_rnd_sol_flw();
  }

}
